### ISSUE TITLE
error running dev on redux@v1.0.0-rc (Sorry it's Windows)

### ISSUE THREAD

**Issue by LarryEitel** [quangbuule/redux-example#10]
```
npm run dev

> redux-example@1.0.0 dev F:\_vms\HomesteadCode\_live\misc\redux-example
> npm run gulp dev


> redux-example@1.0.0 gulp F:\_vms\HomesteadCode\_live\misc\redux-example
> babel-node ./node_modules/gulp/bin/gulp "dev"

[18:32:56] Using gulpfile F:\_vms\HomesteadCode\_live\misc\redux-example\gulpfile.js
[18:32:56] Starting 'dev'...
[18:32:56] Starting 'js:bundle'...
[18:32:59] Finished 'js:bundle' after 3.16 s
[18:32:59] Starting 'watch'...
[18:32:59] Starting 'js:lint'...
[18:32:59] Starting 'js:bundle'...
[18:32:59] Starting 'browser-sync'...
[18:32:59] Finished 'browser-sync' after 65 ms
[18:32:59] Starting 'nodemon'...
[18:32:59] Finished 'nodemon' after 805 μs
[18:32:59] Finished 'watch' after 598 ms
[18:32:59] Finished 'dev' after 3.76 s

> redux-example@1.0.0 express F:\_vms\HomesteadCode\_live\misc\redux-example
> babel-node lib/express

module.js:338
    throw err;
          ^
Error: Cannot find module 'react-router/lib/Location'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (F:/_vms/HomesteadCode/_live/misc/redux-example/lib/render.js:4:53)
    at Module._compile (module.js:460:26)
    at normalLoader (F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "express"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! redux-example@1.0.0 express: `babel-node lib/express`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-example@1.0.0 express script 'babel-node lib/express'.
npm ERR! This is most likely a problem with the redux-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node lib/express
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\_vms\HomesteadCode\_live\misc\redux-example\npm-debug.log
WebpackError
./src/js/main.js
Module not found: Error: Cannot resolve module 'react-router/lib/BrowserHistory' in F:\_vms\HomesteadCode\_live\misc\redux-example\src\js
resolve module react-router/lib/BrowserHistory in F:\_vms\HomesteadCode\_live\misc\redux-example\src\js
  looking for modules in F:\_vms\node_modules
    F:\_vms\node_modules\react-router doesn't exist (module as directory)
  looking for modules in F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules
    resolve 'file' or 'directory' lib/BrowserHistory in F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router
      resolve file
        F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory doesn't exist
        F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory.jsx doesn't exist
        F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory.js doesn't exist
      resolve directory
        F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory doesn't exist (directory default file)
        F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory\package.json doesn't exist (directory description file)
[F:\_vms\node_modules\react-router]
[F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory]
[F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory.jsx]
[F:\_vms\HomesteadCode\_live\misc\redux-example\node_modules\react-router\lib\BrowserHistory.js]
 @ ./src/js/main.js 11:36-78
[18:33:04] Finished jsBundle()
```

**Comment by quangbuule** [comment]
It's not windows' fault, it's caused by new version of react-router (1.0.0-beta4), you can try by installing beta3 ver of react-router:

```
npm install react-router@v1.0.0-beta3
```

**Comment by LarryEitel** [comment]
Thank you @quangbuule. It works now. Thanks for the tip. :)
